name: "Usage ts (js) action"

on:
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: test
        run: echo "Hello, World!"
      - name: Hello world action step
        id: hello
        uses: titoluyo/demo-action-ts@v0.0.4
        with:
          who-to-greet: 'Mona the Octocat'
          milliseconds: 5000
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
